spring.application.name=wallet-service

server.port=8085
server.servlet.context-path=/wallet_service/api
server.compression.enabled=true

# ===============================
# gRPC SERVER CONFIGURATION
# ===============================
grpc.server.port=9095
grpc.server.enable-reflection=true
logging.level.io.grpc=DEBUG
logging.level.io.netty=DEBUG


# Actuator Configuration
management.endpoints.web.exposure.include=health,info,prometheus,metrics
management.endpoint.health.show-details=always
management.endpoints.web.base-path=/actuator
management.endpoints.web.path-mapping.health=health


# Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/central
spring.datasource.username=central
spring.datasource.password=1234
spring.jpa.hibernate.ddl-auto=update

# HikariCP Configuration
spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.idle-timeout=300000
spring.datasource.hikari.max-lifetime=1200000
spring.datasource.hikari.auto-commit=true
spring.datasource.hikari.pool-name=WalletServiceHikariCP


# Logging
logging.level.com.central=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.com.central.wallet_service.scehduler=DEBUG
logging.level.com.zaxxer.hikari=INFO
logging.level.com.zaxxer.hikari.pool=TRACE
logging.level.org.springframework.data.jpa.repository=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE


threading.cpu.pool-size=4
threading.cpu.name-prefix=cpu-pf-
